fix: otlp docs cannot compile.
The bug was introduced since we are compiling grpc files using both tonic and grpcio.

The build logs says:
 thread 'main' panicked at 'Error generating protobuf: Os { code: 30, kind: Other, message: "Read-only file system" }

Thus, we should build the protobuf files into OUT_DIR.

We cannot directly include the protobuf files as tonic does because the files generated by grpcio/protobuf has some attributes like `#![allow(unknown_lints)]`.